#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SadipDAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sadip")]
	public partial class SadipDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcms_template(cms_template instance);
    partial void Updatecms_template(cms_template instance);
    partial void Deletecms_template(cms_template instance);
    partial void Insertcms_component_instance(cms_component_instance instance);
    partial void Updatecms_component_instance(cms_component_instance instance);
    partial void Deletecms_component_instance(cms_component_instance instance);
    partial void Insertcms_component(cms_component instance);
    partial void Updatecms_component(cms_component instance);
    partial void Deletecms_component(cms_component instance);
    partial void Insertcms_component_property(cms_component_property instance);
    partial void Updatecms_component_property(cms_component_property instance);
    partial void Deletecms_component_property(cms_component_property instance);
    partial void Insertcms_component_instance_value(cms_component_instance_value instance);
    partial void Updatecms_component_instance_value(cms_component_instance_value instance);
    partial void Deletecms_component_instance_value(cms_component_instance_value instance);
    partial void Insertcms_page(cms_page instance);
    partial void Updatecms_page(cms_page instance);
    partial void Deletecms_page(cms_page instance);
    #endregion
		
		public SadipDBDataContext() : 
				base(global::SadipDAL.Properties.Settings.Default.SadipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SadipDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SadipDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SadipDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SadipDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cms_template> cms_templates
		{
			get
			{
				return this.GetTable<cms_template>();
			}
		}
		
		public System.Data.Linq.Table<cms_component_instance> cms_component_instances
		{
			get
			{
				return this.GetTable<cms_component_instance>();
			}
		}
		
		public System.Data.Linq.Table<cms_component> cms_components
		{
			get
			{
				return this.GetTable<cms_component>();
			}
		}
		
		public System.Data.Linq.Table<cms_component_property> cms_component_properties
		{
			get
			{
				return this.GetTable<cms_component_property>();
			}
		}
		
		public System.Data.Linq.Table<cms_component_instance_value> cms_component_instance_values
		{
			get
			{
				return this.GetTable<cms_component_instance_value>();
			}
		}
		
		public System.Data.Linq.Table<View_Component> View_Components
		{
			get
			{
				return this.GetTable<View_Component>();
			}
		}
		
		public System.Data.Linq.Table<cms_page> cms_pages
		{
			get
			{
				return this.GetTable<cms_page>();
			}
		}
		
		public System.Data.Linq.Table<View_Page> View_Pages
		{
			get
			{
				return this.GetTable<View_Page>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_template")]
	public partial class cms_template : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _template_id;
		
		private string _template_name;
		
		private string _master_page_url;
		
		private System.Nullable<System.DateTime> _insert_date;
		
		private string _insert_user;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private string _upate_user;
		
		private string _delete_user;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private string _template_css;
		
		private EntitySet<cms_page> _cms_pages;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontemplate_idChanging(int value);
    partial void Ontemplate_idChanged();
    partial void Ontemplate_nameChanging(string value);
    partial void Ontemplate_nameChanged();
    partial void Onmaster_page_urlChanging(string value);
    partial void Onmaster_page_urlChanged();
    partial void Oninsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dateChanged();
    partial void Oninsert_userChanging(string value);
    partial void Oninsert_userChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void Onupate_userChanging(string value);
    partial void Onupate_userChanged();
    partial void Ondelete_userChanging(string value);
    partial void Ondelete_userChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    partial void Ontemplate_cssChanging(string value);
    partial void Ontemplate_cssChanged();
    #endregion
		
		public cms_template()
		{
			this._cms_pages = new EntitySet<cms_page>(new Action<cms_page>(this.attach_cms_pages), new Action<cms_page>(this.detach_cms_pages));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int template_id
		{
			get
			{
				return this._template_id;
			}
			set
			{
				if ((this._template_id != value))
				{
					this.Ontemplate_idChanging(value);
					this.SendPropertyChanging();
					this._template_id = value;
					this.SendPropertyChanged("template_id");
					this.Ontemplate_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_name", DbType="VarChar(50)")]
		public string template_name
		{
			get
			{
				return this._template_name;
			}
			set
			{
				if ((this._template_name != value))
				{
					this.Ontemplate_nameChanging(value);
					this.SendPropertyChanging();
					this._template_name = value;
					this.SendPropertyChanged("template_name");
					this.Ontemplate_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_master_page_url", DbType="VarChar(250)")]
		public string master_page_url
		{
			get
			{
				return this._master_page_url;
			}
			set
			{
				if ((this._master_page_url != value))
				{
					this.Onmaster_page_urlChanging(value);
					this.SendPropertyChanging();
					this._master_page_url = value;
					this.SendPropertyChanged("master_page_url");
					this.Onmaster_page_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this.Oninsert_dateChanging(value);
					this.SendPropertyChanging();
					this._insert_date = value;
					this.SendPropertyChanged("insert_date");
					this.Oninsert_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_user", DbType="VarChar(50)")]
		public string insert_user
		{
			get
			{
				return this._insert_user;
			}
			set
			{
				if ((this._insert_user != value))
				{
					this.Oninsert_userChanging(value);
					this.SendPropertyChanging();
					this._insert_user = value;
					this.SendPropertyChanged("insert_user");
					this.Oninsert_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_upate_user", DbType="VarChar(50)")]
		public string upate_user
		{
			get
			{
				return this._upate_user;
			}
			set
			{
				if ((this._upate_user != value))
				{
					this.Onupate_userChanging(value);
					this.SendPropertyChanging();
					this._upate_user = value;
					this.SendPropertyChanged("upate_user");
					this.Onupate_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_user", DbType="VarChar(50)")]
		public string delete_user
		{
			get
			{
				return this._delete_user;
			}
			set
			{
				if ((this._delete_user != value))
				{
					this.Ondelete_userChanging(value);
					this.SendPropertyChanging();
					this._delete_user = value;
					this.SendPropertyChanged("delete_user");
					this.Ondelete_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_css", DbType="VarChar(250)")]
		public string template_css
		{
			get
			{
				return this._template_css;
			}
			set
			{
				if ((this._template_css != value))
				{
					this.Ontemplate_cssChanging(value);
					this.SendPropertyChanging();
					this._template_css = value;
					this.SendPropertyChanged("template_css");
					this.Ontemplate_cssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_template_cms_page", Storage="_cms_pages", ThisKey="template_id", OtherKey="template_id")]
		public EntitySet<cms_page> cms_pages
		{
			get
			{
				return this._cms_pages;
			}
			set
			{
				this._cms_pages.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cms_pages(cms_page entity)
		{
			this.SendPropertyChanging();
			entity.cms_template = this;
		}
		
		private void detach_cms_pages(cms_page entity)
		{
			this.SendPropertyChanging();
			entity.cms_template = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_component_instance")]
	public partial class cms_component_instance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _component_instance_id;
		
		private System.Nullable<int> _page_id;
		
		private System.Nullable<int> _component_id;
		
		private System.Nullable<int> _template_contentplaceholder_id;
		
		private string _component_position;
		
		private System.Nullable<int> _component_height;
		
		private System.Nullable<int> _component_width;
		
		private System.Nullable<bool> _is_published;
		
		private System.Nullable<bool> _component_active_passive;
		
		private System.Nullable<System.DateTime> _insert_date;
		
		private string _insert_user;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private string _delete_user;
		
		private System.Nullable<System.DateTime> _publish_historyDate;
		
		private EntitySet<cms_component_instance_value> _cms_component_instance_values;
		
		private EntityRef<cms_component> _cms_component;
		
		private EntityRef<cms_page> _cms_page;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomponent_instance_idChanging(int value);
    partial void Oncomponent_instance_idChanged();
    partial void Onpage_idChanging(System.Nullable<int> value);
    partial void Onpage_idChanged();
    partial void Oncomponent_idChanging(System.Nullable<int> value);
    partial void Oncomponent_idChanged();
    partial void Ontemplate_contentplaceholder_idChanging(System.Nullable<int> value);
    partial void Ontemplate_contentplaceholder_idChanged();
    partial void Oncomponent_positionChanging(string value);
    partial void Oncomponent_positionChanged();
    partial void Oncomponent_heightChanging(System.Nullable<int> value);
    partial void Oncomponent_heightChanged();
    partial void Oncomponent_widthChanging(System.Nullable<int> value);
    partial void Oncomponent_widthChanged();
    partial void Onis_publishedChanging(System.Nullable<bool> value);
    partial void Onis_publishedChanged();
    partial void Oncomponent_active_passiveChanging(System.Nullable<bool> value);
    partial void Oncomponent_active_passiveChanged();
    partial void Oninsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dateChanged();
    partial void Oninsert_userChanging(string value);
    partial void Oninsert_userChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    partial void Ondelete_userChanging(string value);
    partial void Ondelete_userChanged();
    partial void Onpublish_historyDateChanging(System.Nullable<System.DateTime> value);
    partial void Onpublish_historyDateChanged();
    #endregion
		
		public cms_component_instance()
		{
			this._cms_component_instance_values = new EntitySet<cms_component_instance_value>(new Action<cms_component_instance_value>(this.attach_cms_component_instance_values), new Action<cms_component_instance_value>(this.detach_cms_component_instance_values));
			this._cms_component = default(EntityRef<cms_component>);
			this._cms_page = default(EntityRef<cms_page>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_instance_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int component_instance_id
		{
			get
			{
				return this._component_instance_id;
			}
			set
			{
				if ((this._component_instance_id != value))
				{
					this.Oncomponent_instance_idChanging(value);
					this.SendPropertyChanging();
					this._component_instance_id = value;
					this.SendPropertyChanged("component_instance_id");
					this.Oncomponent_instance_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_id", DbType="Int")]
		public System.Nullable<int> page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					if (this._cms_page.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_id", DbType="Int")]
		public System.Nullable<int> component_id
		{
			get
			{
				return this._component_id;
			}
			set
			{
				if ((this._component_id != value))
				{
					if (this._cms_component.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncomponent_idChanging(value);
					this.SendPropertyChanging();
					this._component_id = value;
					this.SendPropertyChanged("component_id");
					this.Oncomponent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_contentplaceholder_id", DbType="Int")]
		public System.Nullable<int> template_contentplaceholder_id
		{
			get
			{
				return this._template_contentplaceholder_id;
			}
			set
			{
				if ((this._template_contentplaceholder_id != value))
				{
					this.Ontemplate_contentplaceholder_idChanging(value);
					this.SendPropertyChanging();
					this._template_contentplaceholder_id = value;
					this.SendPropertyChanged("template_contentplaceholder_id");
					this.Ontemplate_contentplaceholder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_position", DbType="VarChar(50)")]
		public string component_position
		{
			get
			{
				return this._component_position;
			}
			set
			{
				if ((this._component_position != value))
				{
					this.Oncomponent_positionChanging(value);
					this.SendPropertyChanging();
					this._component_position = value;
					this.SendPropertyChanged("component_position");
					this.Oncomponent_positionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_height", DbType="Int")]
		public System.Nullable<int> component_height
		{
			get
			{
				return this._component_height;
			}
			set
			{
				if ((this._component_height != value))
				{
					this.Oncomponent_heightChanging(value);
					this.SendPropertyChanging();
					this._component_height = value;
					this.SendPropertyChanged("component_height");
					this.Oncomponent_heightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_width", DbType="Int")]
		public System.Nullable<int> component_width
		{
			get
			{
				return this._component_width;
			}
			set
			{
				if ((this._component_width != value))
				{
					this.Oncomponent_widthChanging(value);
					this.SendPropertyChanging();
					this._component_width = value;
					this.SendPropertyChanged("component_width");
					this.Oncomponent_widthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit")]
		public System.Nullable<bool> is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this.Onis_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_published = value;
					this.SendPropertyChanged("is_published");
					this.Onis_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[component_active/passive]", Storage="_component_active_passive", DbType="Bit")]
		public System.Nullable<bool> component_active_passive
		{
			get
			{
				return this._component_active_passive;
			}
			set
			{
				if ((this._component_active_passive != value))
				{
					this.Oncomponent_active_passiveChanging(value);
					this.SendPropertyChanging();
					this._component_active_passive = value;
					this.SendPropertyChanged("component_active_passive");
					this.Oncomponent_active_passiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this.Oninsert_dateChanging(value);
					this.SendPropertyChanging();
					this._insert_date = value;
					this.SendPropertyChanged("insert_date");
					this.Oninsert_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_user", DbType="VarChar(50)")]
		public string insert_user
		{
			get
			{
				return this._insert_user;
			}
			set
			{
				if ((this._insert_user != value))
				{
					this.Oninsert_userChanging(value);
					this.SendPropertyChanging();
					this._insert_user = value;
					this.SendPropertyChanged("insert_user");
					this.Oninsert_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_user", DbType="VarChar(50)")]
		public string delete_user
		{
			get
			{
				return this._delete_user;
			}
			set
			{
				if ((this._delete_user != value))
				{
					this.Ondelete_userChanging(value);
					this.SendPropertyChanging();
					this._delete_user = value;
					this.SendPropertyChanged("delete_user");
					this.Ondelete_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_publish_historyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> publish_historyDate
		{
			get
			{
				return this._publish_historyDate;
			}
			set
			{
				if ((this._publish_historyDate != value))
				{
					this.Onpublish_historyDateChanging(value);
					this.SendPropertyChanging();
					this._publish_historyDate = value;
					this.SendPropertyChanged("publish_historyDate");
					this.Onpublish_historyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_instance_cms_component_instance_value", Storage="_cms_component_instance_values", ThisKey="component_instance_id", OtherKey="component_instance_id")]
		public EntitySet<cms_component_instance_value> cms_component_instance_values
		{
			get
			{
				return this._cms_component_instance_values;
			}
			set
			{
				this._cms_component_instance_values.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_cms_component_instance", Storage="_cms_component", ThisKey="component_id", OtherKey="component_id", IsForeignKey=true)]
		public cms_component cms_component
		{
			get
			{
				return this._cms_component.Entity;
			}
			set
			{
				cms_component previousValue = this._cms_component.Entity;
				if (((previousValue != value) 
							|| (this._cms_component.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_component.Entity = null;
						previousValue.cms_component_instances.Remove(this);
					}
					this._cms_component.Entity = value;
					if ((value != null))
					{
						value.cms_component_instances.Add(this);
						this._component_id = value.component_id;
					}
					else
					{
						this._component_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_component");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_page_cms_component_instance", Storage="_cms_page", ThisKey="page_id", OtherKey="page_id", IsForeignKey=true)]
		public cms_page cms_page
		{
			get
			{
				return this._cms_page.Entity;
			}
			set
			{
				cms_page previousValue = this._cms_page.Entity;
				if (((previousValue != value) 
							|| (this._cms_page.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_page.Entity = null;
						previousValue.cms_component_instances.Remove(this);
					}
					this._cms_page.Entity = value;
					if ((value != null))
					{
						value.cms_component_instances.Add(this);
						this._page_id = value.page_id;
					}
					else
					{
						this._page_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_page");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cms_component_instance_values(cms_component_instance_value entity)
		{
			this.SendPropertyChanging();
			entity.cms_component_instance = this;
		}
		
		private void detach_cms_component_instance_values(cms_component_instance_value entity)
		{
			this.SendPropertyChanging();
			entity.cms_component_instance = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_component")]
	public partial class cms_component : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _component_id;
		
		private string _component_css;
		
		private string _componen_UserControlName;
		
		private string _component_name;
		
		private EntitySet<cms_component_instance> _cms_component_instances;
		
		private EntitySet<cms_component_property> _cms_component_properties;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomponent_idChanging(int value);
    partial void Oncomponent_idChanged();
    partial void Oncomponent_cssChanging(string value);
    partial void Oncomponent_cssChanged();
    partial void Oncomponen_UserControlNameChanging(string value);
    partial void Oncomponen_UserControlNameChanged();
    partial void Oncomponent_nameChanging(string value);
    partial void Oncomponent_nameChanged();
    #endregion
		
		public cms_component()
		{
			this._cms_component_instances = new EntitySet<cms_component_instance>(new Action<cms_component_instance>(this.attach_cms_component_instances), new Action<cms_component_instance>(this.detach_cms_component_instances));
			this._cms_component_properties = new EntitySet<cms_component_property>(new Action<cms_component_property>(this.attach_cms_component_properties), new Action<cms_component_property>(this.detach_cms_component_properties));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int component_id
		{
			get
			{
				return this._component_id;
			}
			set
			{
				if ((this._component_id != value))
				{
					this.Oncomponent_idChanging(value);
					this.SendPropertyChanging();
					this._component_id = value;
					this.SendPropertyChanged("component_id");
					this.Oncomponent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_css", DbType="VarChar(50)")]
		public string component_css
		{
			get
			{
				return this._component_css;
			}
			set
			{
				if ((this._component_css != value))
				{
					this.Oncomponent_cssChanging(value);
					this.SendPropertyChanging();
					this._component_css = value;
					this.SendPropertyChanged("component_css");
					this.Oncomponent_cssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_componen_UserControlName", DbType="VarChar(50)")]
		public string componen_UserControlName
		{
			get
			{
				return this._componen_UserControlName;
			}
			set
			{
				if ((this._componen_UserControlName != value))
				{
					this.Oncomponen_UserControlNameChanging(value);
					this.SendPropertyChanging();
					this._componen_UserControlName = value;
					this.SendPropertyChanged("componen_UserControlName");
					this.Oncomponen_UserControlNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_name", DbType="VarChar(50)")]
		public string component_name
		{
			get
			{
				return this._component_name;
			}
			set
			{
				if ((this._component_name != value))
				{
					this.Oncomponent_nameChanging(value);
					this.SendPropertyChanging();
					this._component_name = value;
					this.SendPropertyChanged("component_name");
					this.Oncomponent_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_cms_component_instance", Storage="_cms_component_instances", ThisKey="component_id", OtherKey="component_id")]
		public EntitySet<cms_component_instance> cms_component_instances
		{
			get
			{
				return this._cms_component_instances;
			}
			set
			{
				this._cms_component_instances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_cms_component_property", Storage="_cms_component_properties", ThisKey="component_id", OtherKey="component_id")]
		public EntitySet<cms_component_property> cms_component_properties
		{
			get
			{
				return this._cms_component_properties;
			}
			set
			{
				this._cms_component_properties.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cms_component_instances(cms_component_instance entity)
		{
			this.SendPropertyChanging();
			entity.cms_component = this;
		}
		
		private void detach_cms_component_instances(cms_component_instance entity)
		{
			this.SendPropertyChanging();
			entity.cms_component = null;
		}
		
		private void attach_cms_component_properties(cms_component_property entity)
		{
			this.SendPropertyChanging();
			entity.cms_component = this;
		}
		
		private void detach_cms_component_properties(cms_component_property entity)
		{
			this.SendPropertyChanging();
			entity.cms_component = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_component_properties")]
	public partial class cms_component_property : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _component_property_id;
		
		private System.Nullable<int> _component_id;
		
		private string _component_definition;
		
		private string _component_type;
		
		private EntitySet<cms_component_instance_value> _cms_component_instance_values;
		
		private EntityRef<cms_component> _cms_component;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomponent_property_idChanging(int value);
    partial void Oncomponent_property_idChanged();
    partial void Oncomponent_idChanging(System.Nullable<int> value);
    partial void Oncomponent_idChanged();
    partial void Oncomponent_definitionChanging(string value);
    partial void Oncomponent_definitionChanged();
    partial void Oncomponent_typeChanging(string value);
    partial void Oncomponent_typeChanged();
    #endregion
		
		public cms_component_property()
		{
			this._cms_component_instance_values = new EntitySet<cms_component_instance_value>(new Action<cms_component_instance_value>(this.attach_cms_component_instance_values), new Action<cms_component_instance_value>(this.detach_cms_component_instance_values));
			this._cms_component = default(EntityRef<cms_component>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_property_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int component_property_id
		{
			get
			{
				return this._component_property_id;
			}
			set
			{
				if ((this._component_property_id != value))
				{
					this.Oncomponent_property_idChanging(value);
					this.SendPropertyChanging();
					this._component_property_id = value;
					this.SendPropertyChanged("component_property_id");
					this.Oncomponent_property_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_id", DbType="Int")]
		public System.Nullable<int> component_id
		{
			get
			{
				return this._component_id;
			}
			set
			{
				if ((this._component_id != value))
				{
					if (this._cms_component.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncomponent_idChanging(value);
					this.SendPropertyChanging();
					this._component_id = value;
					this.SendPropertyChanged("component_id");
					this.Oncomponent_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_definition", DbType="VarChar(250)")]
		public string component_definition
		{
			get
			{
				return this._component_definition;
			}
			set
			{
				if ((this._component_definition != value))
				{
					this.Oncomponent_definitionChanging(value);
					this.SendPropertyChanging();
					this._component_definition = value;
					this.SendPropertyChanged("component_definition");
					this.Oncomponent_definitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_type", DbType="VarChar(250)")]
		public string component_type
		{
			get
			{
				return this._component_type;
			}
			set
			{
				if ((this._component_type != value))
				{
					this.Oncomponent_typeChanging(value);
					this.SendPropertyChanging();
					this._component_type = value;
					this.SendPropertyChanged("component_type");
					this.Oncomponent_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_property_cms_component_instance_value", Storage="_cms_component_instance_values", ThisKey="component_property_id", OtherKey="component_property_id")]
		public EntitySet<cms_component_instance_value> cms_component_instance_values
		{
			get
			{
				return this._cms_component_instance_values;
			}
			set
			{
				this._cms_component_instance_values.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_cms_component_property", Storage="_cms_component", ThisKey="component_id", OtherKey="component_id", IsForeignKey=true)]
		public cms_component cms_component
		{
			get
			{
				return this._cms_component.Entity;
			}
			set
			{
				cms_component previousValue = this._cms_component.Entity;
				if (((previousValue != value) 
							|| (this._cms_component.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_component.Entity = null;
						previousValue.cms_component_properties.Remove(this);
					}
					this._cms_component.Entity = value;
					if ((value != null))
					{
						value.cms_component_properties.Add(this);
						this._component_id = value.component_id;
					}
					else
					{
						this._component_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_component");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cms_component_instance_values(cms_component_instance_value entity)
		{
			this.SendPropertyChanging();
			entity.cms_component_property = this;
		}
		
		private void detach_cms_component_instance_values(cms_component_instance_value entity)
		{
			this.SendPropertyChanging();
			entity.cms_component_property = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_component_instance_value")]
	public partial class cms_component_instance_value : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _component_instance_value_id;
		
		private System.Nullable<int> _component_property_id;
		
		private System.Nullable<int> _component_instance_id;
		
		private string _value;
		
		private System.Nullable<bool> _is_published;
		
		private System.Nullable<System.DateTime> _insert_date;
		
		private string _insert_user;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private string _delete_user;
		
		private EntityRef<cms_component_instance> _cms_component_instance;
		
		private EntityRef<cms_component_property> _cms_component_property;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncomponent_instance_value_idChanging(int value);
    partial void Oncomponent_instance_value_idChanged();
    partial void Oncomponent_property_idChanging(System.Nullable<int> value);
    partial void Oncomponent_property_idChanged();
    partial void Oncomponent_instance_idChanging(System.Nullable<int> value);
    partial void Oncomponent_instance_idChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    partial void Onis_publishedChanging(System.Nullable<bool> value);
    partial void Onis_publishedChanged();
    partial void Oninsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dateChanged();
    partial void Oninsert_userChanging(string value);
    partial void Oninsert_userChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    partial void Ondelete_userChanging(string value);
    partial void Ondelete_userChanged();
    #endregion
		
		public cms_component_instance_value()
		{
			this._cms_component_instance = default(EntityRef<cms_component_instance>);
			this._cms_component_property = default(EntityRef<cms_component_property>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_instance_value_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int component_instance_value_id
		{
			get
			{
				return this._component_instance_value_id;
			}
			set
			{
				if ((this._component_instance_value_id != value))
				{
					this.Oncomponent_instance_value_idChanging(value);
					this.SendPropertyChanging();
					this._component_instance_value_id = value;
					this.SendPropertyChanged("component_instance_value_id");
					this.Oncomponent_instance_value_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_property_id", DbType="Int")]
		public System.Nullable<int> component_property_id
		{
			get
			{
				return this._component_property_id;
			}
			set
			{
				if ((this._component_property_id != value))
				{
					if (this._cms_component_property.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncomponent_property_idChanging(value);
					this.SendPropertyChanging();
					this._component_property_id = value;
					this.SendPropertyChanged("component_property_id");
					this.Oncomponent_property_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_instance_id", DbType="Int")]
		public System.Nullable<int> component_instance_id
		{
			get
			{
				return this._component_instance_id;
			}
			set
			{
				if ((this._component_instance_id != value))
				{
					if (this._cms_component_instance.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncomponent_instance_idChanging(value);
					this.SendPropertyChanging();
					this._component_instance_id = value;
					this.SendPropertyChanged("component_instance_id");
					this.Oncomponent_instance_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(250)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit")]
		public System.Nullable<bool> is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this.Onis_publishedChanging(value);
					this.SendPropertyChanging();
					this._is_published = value;
					this.SendPropertyChanged("is_published");
					this.Onis_publishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this.Oninsert_dateChanging(value);
					this.SendPropertyChanging();
					this._insert_date = value;
					this.SendPropertyChanged("insert_date");
					this.Oninsert_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_user", DbType="VarChar(50)")]
		public string insert_user
		{
			get
			{
				return this._insert_user;
			}
			set
			{
				if ((this._insert_user != value))
				{
					this.Oninsert_userChanging(value);
					this.SendPropertyChanging();
					this._insert_user = value;
					this.SendPropertyChanged("insert_user");
					this.Oninsert_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_user", DbType="VarChar(250)")]
		public string delete_user
		{
			get
			{
				return this._delete_user;
			}
			set
			{
				if ((this._delete_user != value))
				{
					this.Ondelete_userChanging(value);
					this.SendPropertyChanging();
					this._delete_user = value;
					this.SendPropertyChanged("delete_user");
					this.Ondelete_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_instance_cms_component_instance_value", Storage="_cms_component_instance", ThisKey="component_instance_id", OtherKey="component_instance_id", IsForeignKey=true)]
		public cms_component_instance cms_component_instance
		{
			get
			{
				return this._cms_component_instance.Entity;
			}
			set
			{
				cms_component_instance previousValue = this._cms_component_instance.Entity;
				if (((previousValue != value) 
							|| (this._cms_component_instance.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_component_instance.Entity = null;
						previousValue.cms_component_instance_values.Remove(this);
					}
					this._cms_component_instance.Entity = value;
					if ((value != null))
					{
						value.cms_component_instance_values.Add(this);
						this._component_instance_id = value.component_instance_id;
					}
					else
					{
						this._component_instance_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_component_instance");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_component_property_cms_component_instance_value", Storage="_cms_component_property", ThisKey="component_property_id", OtherKey="component_property_id", IsForeignKey=true)]
		public cms_component_property cms_component_property
		{
			get
			{
				return this._cms_component_property.Entity;
			}
			set
			{
				cms_component_property previousValue = this._cms_component_property.Entity;
				if (((previousValue != value) 
							|| (this._cms_component_property.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_component_property.Entity = null;
						previousValue.cms_component_instance_values.Remove(this);
					}
					this._cms_component_property.Entity = value;
					if ((value != null))
					{
						value.cms_component_instance_values.Add(this);
						this._component_property_id = value.component_property_id;
					}
					else
					{
						this._component_property_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_component_property");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Component")]
	public partial class View_Component
	{
		
		private int _component_id;
		
		private string _component_css;
		
		private string _componen_UserControlName;
		
		private string _component_name;
		
		private string _component_definition;
		
		private System.Nullable<int> _component_instance_id;
		
		private string _value;
		
		private System.Nullable<bool> _is_published;
		
		private System.Nullable<System.DateTime> _insert_date;
		
		private string _insert_user;
		
		private System.Nullable<int> _template_contentplaceholder_id;
		
		private string _component_position;
		
		private System.Nullable<int> _component_height;
		
		private System.Nullable<int> _component_width;
		
		private System.Nullable<bool> _component_active_passive;
		
		private System.Nullable<bool> _Expr1;
		
		private System.Nullable<System.DateTime> _Expr2;
		
		private string _Expr3;
		
		public View_Component()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_id", DbType="Int NOT NULL")]
		public int component_id
		{
			get
			{
				return this._component_id;
			}
			set
			{
				if ((this._component_id != value))
				{
					this._component_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_css", DbType="VarChar(50)")]
		public string component_css
		{
			get
			{
				return this._component_css;
			}
			set
			{
				if ((this._component_css != value))
				{
					this._component_css = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_componen_UserControlName", DbType="VarChar(50)")]
		public string componen_UserControlName
		{
			get
			{
				return this._componen_UserControlName;
			}
			set
			{
				if ((this._componen_UserControlName != value))
				{
					this._componen_UserControlName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_name", DbType="VarChar(50)")]
		public string component_name
		{
			get
			{
				return this._component_name;
			}
			set
			{
				if ((this._component_name != value))
				{
					this._component_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_definition", DbType="VarChar(250)")]
		public string component_definition
		{
			get
			{
				return this._component_definition;
			}
			set
			{
				if ((this._component_definition != value))
				{
					this._component_definition = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_instance_id", DbType="Int")]
		public System.Nullable<int> component_instance_id
		{
			get
			{
				return this._component_instance_id;
			}
			set
			{
				if ((this._component_instance_id != value))
				{
					this._component_instance_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="VarChar(250)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this._value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit")]
		public System.Nullable<bool> is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this._insert_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_user", DbType="VarChar(50)")]
		public string insert_user
		{
			get
			{
				return this._insert_user;
			}
			set
			{
				if ((this._insert_user != value))
				{
					this._insert_user = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_contentplaceholder_id", DbType="Int")]
		public System.Nullable<int> template_contentplaceholder_id
		{
			get
			{
				return this._template_contentplaceholder_id;
			}
			set
			{
				if ((this._template_contentplaceholder_id != value))
				{
					this._template_contentplaceholder_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_position", DbType="VarChar(50)")]
		public string component_position
		{
			get
			{
				return this._component_position;
			}
			set
			{
				if ((this._component_position != value))
				{
					this._component_position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_height", DbType="Int")]
		public System.Nullable<int> component_height
		{
			get
			{
				return this._component_height;
			}
			set
			{
				if ((this._component_height != value))
				{
					this._component_height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_width", DbType="Int")]
		public System.Nullable<int> component_width
		{
			get
			{
				return this._component_width;
			}
			set
			{
				if ((this._component_width != value))
				{
					this._component_width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[component_active/passive]", Storage="_component_active_passive", DbType="Bit")]
		public System.Nullable<bool> component_active_passive
		{
			get
			{
				return this._component_active_passive;
			}
			set
			{
				if ((this._component_active_passive != value))
				{
					this._component_active_passive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr1", DbType="Bit")]
		public System.Nullable<bool> Expr1
		{
			get
			{
				return this._Expr1;
			}
			set
			{
				if ((this._Expr1 != value))
				{
					this._Expr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr2", DbType="DateTime")]
		public System.Nullable<System.DateTime> Expr2
		{
			get
			{
				return this._Expr2;
			}
			set
			{
				if ((this._Expr2 != value))
				{
					this._Expr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expr3", DbType="VarChar(50)")]
		public string Expr3
		{
			get
			{
				return this._Expr3;
			}
			set
			{
				if ((this._Expr3 != value))
				{
					this._Expr3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.cms_page")]
	public partial class cms_page : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _page_id;
		
		private string _page_name;
		
		private string _page_url;
		
		private string _page_title;
		
		private string _page_meta;
		
		private string _page_css;
		
		private string _page_javascript;
		
		private string _page_parameters;
		
		private string _page_subpage;
		
		private System.Nullable<int> _subdomain_id;
		
		private System.Nullable<int> _template_id;
		
		private string _parent_page;
		
		private System.Nullable<System.DateTime> _insert_date;
		
		private string _insert_user;
		
		private string _update_user;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private System.Nullable<System.DateTime> _delete_date;
		
		private string _delete_user;
		
		private System.Nullable<bool> _is_deleted;
		
		private EntitySet<cms_component_instance> _cms_component_instances;
		
		private EntityRef<cms_template> _cms_template;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpage_idChanging(int value);
    partial void Onpage_idChanged();
    partial void Onpage_nameChanging(string value);
    partial void Onpage_nameChanged();
    partial void Onpage_urlChanging(string value);
    partial void Onpage_urlChanged();
    partial void Onpage_titleChanging(string value);
    partial void Onpage_titleChanged();
    partial void Onpage_metaChanging(string value);
    partial void Onpage_metaChanged();
    partial void Onpage_cssChanging(string value);
    partial void Onpage_cssChanged();
    partial void Onpage_javascriptChanging(string value);
    partial void Onpage_javascriptChanged();
    partial void Onpage_parametersChanging(string value);
    partial void Onpage_parametersChanged();
    partial void Onpage_subpageChanging(string value);
    partial void Onpage_subpageChanged();
    partial void Onsubdomain_idChanging(System.Nullable<int> value);
    partial void Onsubdomain_idChanged();
    partial void Ontemplate_idChanging(System.Nullable<int> value);
    partial void Ontemplate_idChanged();
    partial void Onparent_pageChanging(string value);
    partial void Onparent_pageChanged();
    partial void Oninsert_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oninsert_dateChanged();
    partial void Oninsert_userChanging(string value);
    partial void Oninsert_userChanged();
    partial void Onupdate_userChanging(string value);
    partial void Onupdate_userChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void Ondelete_dateChanging(System.Nullable<System.DateTime> value);
    partial void Ondelete_dateChanged();
    partial void Ondelete_userChanging(string value);
    partial void Ondelete_userChanged();
    partial void Onis_deletedChanging(System.Nullable<bool> value);
    partial void Onis_deletedChanged();
    #endregion
		
		public cms_page()
		{
			this._cms_component_instances = new EntitySet<cms_component_instance>(new Action<cms_component_instance>(this.attach_cms_component_instances), new Action<cms_component_instance>(this.detach_cms_component_instances));
			this._cms_template = default(EntityRef<cms_template>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this.Onpage_idChanging(value);
					this.SendPropertyChanging();
					this._page_id = value;
					this.SendPropertyChanged("page_id");
					this.Onpage_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_name", DbType="VarChar(250)")]
		public string page_name
		{
			get
			{
				return this._page_name;
			}
			set
			{
				if ((this._page_name != value))
				{
					this.Onpage_nameChanging(value);
					this.SendPropertyChanging();
					this._page_name = value;
					this.SendPropertyChanged("page_name");
					this.Onpage_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_url", DbType="VarChar(250)")]
		public string page_url
		{
			get
			{
				return this._page_url;
			}
			set
			{
				if ((this._page_url != value))
				{
					this.Onpage_urlChanging(value);
					this.SendPropertyChanging();
					this._page_url = value;
					this.SendPropertyChanged("page_url");
					this.Onpage_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_title", DbType="VarChar(250)")]
		public string page_title
		{
			get
			{
				return this._page_title;
			}
			set
			{
				if ((this._page_title != value))
				{
					this.Onpage_titleChanging(value);
					this.SendPropertyChanging();
					this._page_title = value;
					this.SendPropertyChanged("page_title");
					this.Onpage_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_meta", DbType="VarChar(250)")]
		public string page_meta
		{
			get
			{
				return this._page_meta;
			}
			set
			{
				if ((this._page_meta != value))
				{
					this.Onpage_metaChanging(value);
					this.SendPropertyChanging();
					this._page_meta = value;
					this.SendPropertyChanged("page_meta");
					this.Onpage_metaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_css", DbType="VarChar(250)")]
		public string page_css
		{
			get
			{
				return this._page_css;
			}
			set
			{
				if ((this._page_css != value))
				{
					this.Onpage_cssChanging(value);
					this.SendPropertyChanging();
					this._page_css = value;
					this.SendPropertyChanged("page_css");
					this.Onpage_cssChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_javascript", DbType="VarChar(150)")]
		public string page_javascript
		{
			get
			{
				return this._page_javascript;
			}
			set
			{
				if ((this._page_javascript != value))
				{
					this.Onpage_javascriptChanging(value);
					this.SendPropertyChanging();
					this._page_javascript = value;
					this.SendPropertyChanged("page_javascript");
					this.Onpage_javascriptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_parameters", DbType="VarChar(150)")]
		public string page_parameters
		{
			get
			{
				return this._page_parameters;
			}
			set
			{
				if ((this._page_parameters != value))
				{
					this.Onpage_parametersChanging(value);
					this.SendPropertyChanging();
					this._page_parameters = value;
					this.SendPropertyChanged("page_parameters");
					this.Onpage_parametersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_subpage", DbType="VarChar(250)")]
		public string page_subpage
		{
			get
			{
				return this._page_subpage;
			}
			set
			{
				if ((this._page_subpage != value))
				{
					this.Onpage_subpageChanging(value);
					this.SendPropertyChanging();
					this._page_subpage = value;
					this.SendPropertyChanged("page_subpage");
					this.Onpage_subpageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subdomain_id", DbType="Int")]
		public System.Nullable<int> subdomain_id
		{
			get
			{
				return this._subdomain_id;
			}
			set
			{
				if ((this._subdomain_id != value))
				{
					this.Onsubdomain_idChanging(value);
					this.SendPropertyChanging();
					this._subdomain_id = value;
					this.SendPropertyChanged("subdomain_id");
					this.Onsubdomain_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_id", DbType="Int")]
		public System.Nullable<int> template_id
		{
			get
			{
				return this._template_id;
			}
			set
			{
				if ((this._template_id != value))
				{
					if (this._cms_template.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontemplate_idChanging(value);
					this.SendPropertyChanging();
					this._template_id = value;
					this.SendPropertyChanged("template_id");
					this.Ontemplate_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_page", DbType="VarChar(250)")]
		public string parent_page
		{
			get
			{
				return this._parent_page;
			}
			set
			{
				if ((this._parent_page != value))
				{
					this.Onparent_pageChanging(value);
					this.SendPropertyChanging();
					this._parent_page = value;
					this.SendPropertyChanged("parent_page");
					this.Onparent_pageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> insert_date
		{
			get
			{
				return this._insert_date;
			}
			set
			{
				if ((this._insert_date != value))
				{
					this.Oninsert_dateChanging(value);
					this.SendPropertyChanging();
					this._insert_date = value;
					this.SendPropertyChanged("insert_date");
					this.Oninsert_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insert_user", DbType="VarChar(50)")]
		public string insert_user
		{
			get
			{
				return this._insert_user;
			}
			set
			{
				if ((this._insert_user != value))
				{
					this.Oninsert_userChanging(value);
					this.SendPropertyChanging();
					this._insert_user = value;
					this.SendPropertyChanged("insert_user");
					this.Oninsert_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_user", DbType="VarChar(50)")]
		public string update_user
		{
			get
			{
				return this._update_user;
			}
			set
			{
				if ((this._update_user != value))
				{
					this.Onupdate_userChanging(value);
					this.SendPropertyChanging();
					this._update_user = value;
					this.SendPropertyChanged("update_user");
					this.Onupdate_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> delete_date
		{
			get
			{
				return this._delete_date;
			}
			set
			{
				if ((this._delete_date != value))
				{
					this.Ondelete_dateChanging(value);
					this.SendPropertyChanging();
					this._delete_date = value;
					this.SendPropertyChanged("delete_date");
					this.Ondelete_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_delete_user", DbType="VarChar(50)")]
		public string delete_user
		{
			get
			{
				return this._delete_user;
			}
			set
			{
				if ((this._delete_user != value))
				{
					this.Ondelete_userChanging(value);
					this.SendPropertyChanging();
					this._delete_user = value;
					this.SendPropertyChanged("delete_user");
					this.Ondelete_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this.Onis_deletedChanging(value);
					this.SendPropertyChanging();
					this._is_deleted = value;
					this.SendPropertyChanged("is_deleted");
					this.Onis_deletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_page_cms_component_instance", Storage="_cms_component_instances", ThisKey="page_id", OtherKey="page_id")]
		public EntitySet<cms_component_instance> cms_component_instances
		{
			get
			{
				return this._cms_component_instances;
			}
			set
			{
				this._cms_component_instances.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cms_template_cms_page", Storage="_cms_template", ThisKey="template_id", OtherKey="template_id", IsForeignKey=true)]
		public cms_template cms_template
		{
			get
			{
				return this._cms_template.Entity;
			}
			set
			{
				cms_template previousValue = this._cms_template.Entity;
				if (((previousValue != value) 
							|| (this._cms_template.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cms_template.Entity = null;
						previousValue.cms_pages.Remove(this);
					}
					this._cms_template.Entity = value;
					if ((value != null))
					{
						value.cms_pages.Add(this);
						this._template_id = value.template_id;
					}
					else
					{
						this._template_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("cms_template");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_cms_component_instances(cms_component_instance entity)
		{
			this.SendPropertyChanging();
			entity.cms_page = this;
		}
		
		private void detach_cms_component_instances(cms_component_instance entity)
		{
			this.SendPropertyChanging();
			entity.cms_page = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Page")]
	public partial class View_Page
	{
		
		private System.Nullable<int> _template_id;
		
		private string _template_name;
		
		private System.Nullable<int> _page_id;
		
		private string _page_name;
		
		private string _page_url;
		
		private System.Nullable<bool> _is_deleted;
		
		private string _component_name;
		
		private string _component_position;
		
		private System.Nullable<int> _component_height;
		
		private System.Nullable<int> _component_width;
		
		private System.Nullable<bool> _is_published;
		
		private System.Nullable<bool> _component_active_passive;
		
		private string _componen_UserControlName;
		
		private string _component_css;
		
		public View_Page()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_id", DbType="Int")]
		public System.Nullable<int> template_id
		{
			get
			{
				return this._template_id;
			}
			set
			{
				if ((this._template_id != value))
				{
					this._template_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_template_name", DbType="VarChar(50)")]
		public string template_name
		{
			get
			{
				return this._template_name;
			}
			set
			{
				if ((this._template_name != value))
				{
					this._template_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_id", DbType="Int")]
		public System.Nullable<int> page_id
		{
			get
			{
				return this._page_id;
			}
			set
			{
				if ((this._page_id != value))
				{
					this._page_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_name", DbType="VarChar(250)")]
		public string page_name
		{
			get
			{
				return this._page_name;
			}
			set
			{
				if ((this._page_name != value))
				{
					this._page_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_url", DbType="VarChar(250)")]
		public string page_url
		{
			get
			{
				return this._page_url;
			}
			set
			{
				if ((this._page_url != value))
				{
					this._page_url = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_deleted", DbType="Bit")]
		public System.Nullable<bool> is_deleted
		{
			get
			{
				return this._is_deleted;
			}
			set
			{
				if ((this._is_deleted != value))
				{
					this._is_deleted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_name", DbType="VarChar(50)")]
		public string component_name
		{
			get
			{
				return this._component_name;
			}
			set
			{
				if ((this._component_name != value))
				{
					this._component_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_position", DbType="VarChar(50)")]
		public string component_position
		{
			get
			{
				return this._component_position;
			}
			set
			{
				if ((this._component_position != value))
				{
					this._component_position = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_height", DbType="Int")]
		public System.Nullable<int> component_height
		{
			get
			{
				return this._component_height;
			}
			set
			{
				if ((this._component_height != value))
				{
					this._component_height = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_width", DbType="Int")]
		public System.Nullable<int> component_width
		{
			get
			{
				return this._component_width;
			}
			set
			{
				if ((this._component_width != value))
				{
					this._component_width = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit")]
		public System.Nullable<bool> is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[component_active/passive]", Storage="_component_active_passive", DbType="Bit")]
		public System.Nullable<bool> component_active_passive
		{
			get
			{
				return this._component_active_passive;
			}
			set
			{
				if ((this._component_active_passive != value))
				{
					this._component_active_passive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_componen_UserControlName", DbType="VarChar(250)")]
		public string componen_UserControlName
		{
			get
			{
				return this._componen_UserControlName;
			}
			set
			{
				if ((this._componen_UserControlName != value))
				{
					this._componen_UserControlName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_css", DbType="VarChar(250)")]
		public string component_css
		{
			get
			{
				return this._component_css;
			}
			set
			{
				if ((this._component_css != value))
				{
					this._component_css = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
